### PR TITLE
Adding-readme-file_Yaakov-Lerer_CU-1ua3m4z

### PR DESCRIPTION
**Pull request by Lerer**
Adding the readme to the main branch

### CODE REVIEW

**Review by Lerer — COMMENTED** [review]
I reviewed the changes and OK with it

**Review by lerer-reviewer — APPROVED** [review]
NP

**Review by lerer-reviewer — APPROVED** [review]
OK

**Review by lerer-reviewer — APPROVED** [review]
All good

**Review by lerer-reviewer — APPROVED** [review]
All still good

**Pull request merged**
